// Author
const AUTHOR_NAME_MIN_LENGTH = 1;
const AUTHOR_NAME_MAX_LENGTH = 100;
const AUTHOR_USERNAME_MIN_LENGTH = 2;
const AUTHOR_USERNAME_MAX_LENGTH = 50;
const AUTHOR_BIO_MIN_LENGTH = 10;
const AUTHOR_BIO_MAX_LENGTH = 500;

// Category
const CATEGORY_TITLE_MIN_LENGTH = 2;
const CATEGORY_TITLE_MAX_LENGTH = 50;
const CATEGORY_DESCRIPTION_MIN_LENGTH = 10;
const CATEGORY_DESCRIPTION_MAX_LENGTH = 150;

// Idea
const IDEA_SLUG_MAX_LENGTH = 75;
const IDEA_TITLE_MIN_LENGTH = 3;
const IDEA_TITLE_MAX_LENGTH = 100;
const IDEA_SUMMARY_MIN_LENGTH = 20;
const IDEA_SUMMARY_MAX_LENGTH = 500;
const IDEA_CONTENT_MIN_LENGTH = 100;
const IDEA_CONTENT_MAX_LENGTH = 10000;

export {
  AUTHOR_BIO_MAX_LENGTH,
  AUTHOR_BIO_MIN_LENGTH,
  AUTHOR_NAME_MAX_LENGTH,
  AUTHOR_NAME_MIN_LENGTH,
  AUTHOR_USERNAME_MAX_LENGTH,
  AUTHOR_USERNAME_MIN_LENGTH,
  CATEGORY_DESCRIPTION_MAX_LENGTH,
  CATEGORY_DESCRIPTION_MIN_LENGTH,
  CATEGORY_TITLE_MAX_LENGTH,
  CATEGORY_TITLE_MIN_LENGTH,
  IDEA_CONTENT_MAX_LENGTH,
  IDEA_CONTENT_MIN_LENGTH,
  IDEA_SLUG_MAX_LENGTH,
  IDEA_SUMMARY_MAX_LENGTH,
  IDEA_SUMMARY_MIN_LENGTH,
  IDEA_TITLE_MAX_LENGTH,
  IDEA_TITLE_MIN_LENGTH,
};
